const ICELAND_LOCATIONS = [
  // Cities
  { id:1,  name:'Reykjavík',       en:'Reykjavik',              lat:64.1466, lng:-21.9426, category:'city',     desc:'Capital and largest city. The name means "Smoky Bay", named after steam rising from hot springs seen by the first settlers.' },
  { id:2,  name:'Akureyri',        en:'Akureyri',               lat:65.6835, lng:-18.0878, category:'city',     desc:'"Capital of the North" and Iceland\'s second city. Situated at the end of Eyjafjörður fjord. The name may mean "Field of the River\'s Mouth".' },
  { id:3,  name:'Hafnarfjörður',   en:'Hafnarfjordur',          lat:64.0674, lng:-21.9590, category:'city',     desc:'"Harbour Fjord" — a port town on the Reykjanes Peninsula, known as the "Town of Lava and Elves".' },
  { id:4,  name:'Kópavogur',       en:'Kopavogur',              lat:64.1136, lng:-21.9058, category:'city',     desc:'Second most populous city, part of the Capital Region. The name means "Seal Pup Bay".' },
  { id:5,  name:'Selfoss',         en:'Selfoss',                lat:63.9337, lng:-20.9965, category:'city',     desc:'Largest town in South Iceland on the Ölfusá river. The name means "Waterfall of the Seil River".' },
  { id:6,  name:'Höfn',            en:'Hofn',                   lat:64.2539, lng:-15.2099, category:'city',     desc:'"Harbour" — a small fishing town in Southeast Iceland famous for langoustine (humar). Gateway to Vatnajökull.' },
  { id:7,  name:'Ísafjörður',      en:'Isafjordur',             lat:66.0742, lng:-23.1308, category:'city',     desc:'"Ice Fjord" — the largest town in the remote Westfjords region, population around 2,600.' },
  { id:8,  name:'Egilsstaðir',     en:'Egilsstadir',            lat:65.2673, lng:-14.3948, category:'city',     desc:'Largest town in East Iceland on the Lagarfljót river. The name means "Egill\'s Farmstead".' },
  { id:9,  name:'Vestmannaeyjar',  en:'Westman Islands',        lat:63.4427, lng:-20.2769, category:'city',     desc:'"Islands of the Westmen" — an archipelago off the south coast. Famous for the 1973 Eldfell eruption that buried part of the town.' },
  { id:10, name:'Húsavík',         en:'Husavik',                lat:65.9519, lng:-17.3397, category:'city',     desc:'"Bay of Houses" — Iceland\'s whale-watching capital on the north coast, with one of the oldest settled harbours.' },
  { id:11, name:'Borgarnes',       en:'Borgarnes',              lat:64.5376, lng:-21.9227, category:'city',     desc:'"Town of the Fortress" — in West Iceland on Borgarfjörður. The Settlement Centre museum tells the saga of Egill Skallagrímsson.' },
  { id:12, name:'Vík í Mýrdal',    en:'Vik',                    lat:63.4186, lng:-18.9981, category:'city',     desc:'Iceland\'s southernmost village, meaning "Bay in Mire Valley". Famous for its dramatic black sand beach and basalt sea stacks.' },
  { id:13, name:'Siglufjörður',    en:'Siglufjordur',           lat:66.1504, lng:-18.9104, category:'city',     desc:'"Strait Fjord" — a picturesque fishing town. Was once the herring capital of Iceland during the herring boom of the 20th century.' },
  { id:14, name:'Stykkishólmur',   en:'Stykkisholmur',          lat:65.0736, lng:-22.7298, category:'city',     desc:'"Stack Isle Holm" — a charming harbour town on Snæfellsnes Peninsula with colourful houses and island-dotted bay.' },
  { id:15, name:'Sauðárkrókur',    en:'Saudarkrokur',           lat:65.7452, lng:-19.6383, category:'city',     desc:'"Sheep River Bend" — the second largest town in North Iceland. Centre of the Skagafjörður region known for horse breeding.' },

  // Nature
  { id:20, name:'Þingvellir',      en:'Thingvellir',            lat:64.2553, lng:-21.1298, category:'nature',   desc:'UNESCO World Heritage Site and national park where the North American and Eurasian tectonic plates meet. Site of the original Alþingi parliament (930 AD). Name means "Parliament Plains".' },
  { id:21, name:'Geysir',          en:'Geysir (Great Geysir)',  lat:64.3101, lng:-20.3006, category:'nature',   desc:'The original geyser that gave all geysers their name — from the Old Norse "gjósa" meaning "to gush". Now mostly dormant, but the nearby Strokkur geyser erupts every 5–10 minutes.' },
  { id:22, name:'Gullfoss',        en:'Golden Falls',           lat:64.3271, lng:-20.1207, category:'nature',   desc:'"Golden Falls" — one of Iceland\'s most iconic waterfalls, plunging 32m into a deep canyon. Part of the famous Golden Circle route.' },
  { id:23, name:'Seljalandsfoss',  en:'Seljalandsfoss',         lat:63.6156, lng:-19.9907, category:'nature',   desc:'A spectacular 60m waterfall you can walk behind. Named after the Seljalands river. One of Iceland\'s most photographed sights.' },
  { id:24, name:'Skógafoss',       en:'Skogafoss',              lat:63.5320, lng:-19.5138, category:'nature',   desc:'"Forest Waterfall" — a massive 25m wide, 60m drop waterfall. Legend says a treasure chest is hidden behind it. 527 steps lead to the top.' },
  { id:25, name:'Jökulsárlón',     en:'Glacial River Lagoon',   lat:64.0784, lng:-16.2306, category:'nature',   desc:'"Glacial River Lagoon" — filled with blue icebergs calved from Breiðamerkurjökull glacier. Icebergs wash onto the nearby "Diamond Beach".' },
  { id:26, name:'Mývatn',          en:'Midge Lake',             lat:65.6001, lng:-17.0000, category:'nature',   desc:'"Midge Lake" — a shallow lake in North Iceland surrounded by lava pillars, pseudo-craters, hot springs, and extraordinary birdlife. A volcanic wonderland.' },
  { id:27, name:'Dettifoss',       en:'Dettifoss',              lat:65.8145, lng:-16.3848, category:'nature',   desc:'Europe\'s most powerful waterfall by volume — 45m high and up to 500 m³/s flow. The name may come from an old word for "tumbling" or "thunderous".' },
  { id:28, name:'Goðafoss',        en:'Waterfall of the Gods',  lat:65.6824, lng:-17.5518, category:'nature',   desc:'"Waterfall of the Gods" — named after the year 1000 AD, when the lawspeaker Þorgeir Ljósvetningagoði cast Norse idols into it after Iceland adopted Christianity.' },
  { id:29, name:'Dyrhólaey',       en:'Dyrholaey',              lat:63.4040, lng:-19.1296, category:'nature',   desc:'"Door Hill Island" — a rocky peninsula with a natural arch large enough for small aircraft to fly through. Great puffin nesting site in summer.' },
  { id:30, name:'Reynisfjara',     en:'Reynisfjara Black Beach', lat:63.4063, lng:-19.0461, category:'nature',  desc:'Famous black basalt sand beach with towering Reynisdrangar sea stacks and Hálsanef basalt column cave. Warning: unpredictable "sneaker waves".' },
  { id:31, name:'Landmannalaugar', en:'Landmannalaugar',        lat:63.9846, lng:-19.0630, category:'nature',   desc:'"The People\'s Pool" — a remote highland area with naturally heated geothermal pools surrounded by multicoloured rhyolite mountains. Start of the Laugavegur hiking trail.' },
  { id:32, name:'Þórsmörk',        en:'Thorsmork',              lat:63.7069, lng:-19.5110, category:'nature',   desc:'"Thor\'s Forest" — a glacial valley surrounded by three glaciers: Mýrdalsjökull, Eyjafjallajökull, and Tindfjallajökull. End point of the Laugavegur trail.' },
  { id:33, name:'Svartifoss',      en:'Black Waterfall',        lat:64.0234, lng:-16.9754, category:'nature',   desc:'"Black Waterfall" — framed by striking dark basalt columns in Skaftafell. It inspired architect Guðjón Samúelsson\'s design for Hallgrímskirkja church.' },
  { id:34, name:'Glymur',          en:'Glymur',                 lat:64.3982, lng:-21.2777, category:'nature',   desc:'Iceland\'s second highest waterfall at 198m. The name means "Rumble" or "Noise". Hidden in Hvalfjörður and requires a river crossing hike to reach.' },

  // Glaciers
  { id:40, name:'Vatnajökull',     en:'Vatnajokull Glacier',    lat:64.4000, lng:-16.9000, category:'glacier',  desc:'"Glacier of Lakes" — the largest glacier in Iceland and Europe by volume. Covers roughly 8% of Iceland. Contains several active volcanoes beneath its ice.' },
  { id:41, name:'Snæfellsjökull',  en:'Snaefellsjokull',        lat:64.8081, lng:-23.7700, category:'glacier',  desc:'"Snow Mountain Glacier" — a stratovolcano glacier at the tip of Snæfellsnes. Jules Verne\'s "Journey to the Center of the Earth" begins here. Believed to have mystical energy.' },
  { id:42, name:'Langjökull',      en:'Long Glacier',           lat:64.6667, lng:-20.0000, category:'glacier',  desc:'"Long Glacier" — Iceland\'s second largest glacier. Features a man-made ice tunnel you can explore inside. The "Into the Glacier" attraction is cut deep within it.' },
  { id:43, name:'Mýrdalsjökull',   en:'Myrdalsjokull',          lat:63.6667, lng:-19.1000, category:'glacier',  desc:'"Swamp Dale Glacier" — covers the Katla volcano. When Katla erupts beneath it, the resulting glacial flood (jökulhlaup) can be catastrophic.' },

  // Volcanoes
  { id:50, name:'Hekla',           en:'Hekla',                  lat:63.9889, lng:-19.6661, category:'volcano',  desc:'One of Iceland\'s most active volcanoes. Known in medieval Europe as the "Gateway to Hell". Has erupted over 20 times since 874 AD. Last erupted in 2000.' },
  { id:51, name:'Katla',           en:'Katla',                  lat:63.6333, lng:-19.1667, category:'volcano',  desc:'A major subglacial volcano beneath Mýrdalsjökull. Historically erupts every 40–80 years. The name may mean "Kettle". Overdue for an eruption.' },
  { id:52, name:'Askja',           en:'Askja',                  lat:65.0366, lng:-16.7533, category:'volcano',  desc:'A large volcanic caldera in the central highlands. Apollo astronauts trained here in 1965 due to its lunar-like landscape. Contains the crater lake Víti ("Hell").' },
  { id:53, name:'Eyjafjallajökull', en:'Eyjafjallajokull',      lat:63.6333, lng:-19.6000, category:'volcano',  desc:'"Glacier of the Island Mountains" — famous for its 2010 eruption that disrupted European air travel for weeks. A tongue-twister for non-Icelandic speakers.' },
  { id:54, name:'Krafla',          en:'Krafla',                 lat:65.7167, lng:-16.7833, category:'volcano',  desc:'Volcanic caldera in Northeast Iceland near Mývatn. Experienced the "Krafla Fires" eruption series from 1975–1984. Features boiling mud pools and steaming vents.' },
  { id:55, name:'Eldgjá',          en:'Eldgja Fire Canyon',     lat:63.9833, lng:-18.6333, category:'volcano',  desc:'"Fire Canyon" — the world\'s largest volcanic canyon, part of the Katla system. The 934 AD eruption was one of the largest in human history, causing famines across Europe.' },

  // Landmarks & Hot Springs
  { id:60, name:'Bláa Lónið',      en:'Blue Lagoon',            lat:63.8804, lng:-22.4490, category:'landmark', desc:'"Blue Lagoon" — an iconic geothermal spa in a lava field on the Reykjanes Peninsula. The milky-blue water is rich in silica and sulfur, fed by a nearby geothermal plant.' },
  { id:61, name:'Gamla Laugin',    en:'Secret Lagoon',          lat:64.1291, lng:-20.2963, category:'landmark', desc:'"Old Pool" — Iceland\'s oldest swimming pool (1891) in Flúðir. A naturally heated geothermal pool with a small geyser. Much less crowded than the Blue Lagoon.' },
  { id:62, name:'Bessastaðir',     en:'Bessastadir',            lat:64.0949, lng:-22.0305, category:'landmark', desc:'The official residence of the President of Iceland. A historic estate dating to medieval times, with a turf-roofed church from 1774.' },
  { id:63, name:'Eiríksstaðir',    en:'Eiriksstadid',           lat:65.0720, lng:-21.8930, category:'landmark', desc:'A reconstructed Viking longhouse — the birthplace of Leif Erikson, the Norse explorer who reached North America around 1000 AD, nearly 500 years before Columbus.' },
  { id:64, name:'Skálholt',        en:'Skalholt',               lat:64.1197, lng:-20.5203, category:'landmark', desc:'Iceland\'s most important historical and ecclesiastical site, serving as a bishopric from 1056 to 1801. Features a modern cathedral built over the ancient site.' },
  { id:65, name:'Snæfellsnes',     en:'Snaefellsnes Peninsula', lat:64.8579, lng:-23.9316, category:'landmark', desc:'"Snow Mountain Peninsula" — often called "Iceland in miniature": glaciers, lava fields, fishing villages, black beaches, and bird cliffs all in one compact peninsula.' },
];

export default ICELAND_LOCATIONS;
